#%RAML 1.0
title: ISO Data Service (isodata)
description: Basic service providing read access to basic standard data like countries, currencies, languages and measure units.
version: 1.0.0
baseUri: http://localhost
mediaType:
  - application/json
protocols:
  - http
  - https

types: !include schemas/index.raml
traits:
    acceptLanguage: !include traits/acceptLanguage.raml
    sendNotFound: !include traits/sendNotFound.raml

/countries: !include resourceTypes/country.raml
/currencies: !include resourceTypes/currency.raml
/languages: !include resourceTypes/language.raml
