Country: !include Country.raml
CountryMap: !include CountryMap.raml
Currency: !include Currency.raml
CurrencyMap: !include CurrencyMap.raml
Language: !include Language.raml
LanguageMap: !include LanguageMap.raml
Error: !include Error.raml
